version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: com.mojang:minecraft
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"