modLoader = "kotlinforforge"
loaderVersion = "[5.5,)"
license = "MPL-2.0"
issueTrackerURL = "https://github.com/wanderia/netlib/issues"

[[mods]]
modId = "netlib"
version = "$version"
description = '''
Kotlinx Serialization for custom payloads.
'''
logoFile = "wanderia-netlib.png"
updateJSONURL = "https://api.modrinth.com/updates/netlib/forge_updates.json"
displayURL = "https://modrinth.com/mod/netlib"

[[dependencies.netlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
