name: Build (Pull Request)

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build, Test, and Check
        run: ./gradlew build test spotlessCheck
